name: Eval

on:
  workflow_dispatch:

jobs:
  eval:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run holdout validation
      id: holdout
      run: |
        metrics=$(python -m src.eval.backtest holdout data/processed/features.csv models/best_model.pkl 2024-01-01)
        echo "$metrics"
        echo "metrics=$metrics" >> $GITHUB_OUTPUT

